### PR TITLE
Move insert halt at end to assemble_from_file

### PR DESCRIPTION
**Pull request by mlouielu**

### CODE REVIEW

**Comment by jserv** [comment]
What is the motivation?

**Comment by mlouielu** [comment]
since `driver.c` should allow to be replaceable, I think halt should auto insert into the end of the file.

Or maybe we could propose another approach, when dispatch to the end of the instruction, eval loop will break out without halt instuction.

**Comment by jserv** [comment]
@mlouielu, It is time to learn how CPython internals work and "cherry-pick" ideas to this project as testbed.

**Comment by mlouielu** [comment]
@jserv yep, I borrow some implement method from CPython.

**Comment by mlouielu** [comment]
Close this issue, propose #10 for better implement.

**Pull request closed without merging**
